package com.scyllamobile.model;
// Generated Jun 8, 2017 5:46:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Devices generated by hbm2java
 */
public class Devices  implements java.io.Serializable {


     private BigDecimal id;
     private Users users;
     private String code;
     private String description;
     private String macAddress;
     private Long status;

    public Devices() {
    }

	
    public Devices(BigDecimal id) {
        this.id = id;
    }
    public Devices(BigDecimal id, Users users, String code, String description, String macAddress, Long status) {
       this.id = id;
       this.users = users;
       this.code = code;
       this.description = description;
       this.macAddress = macAddress;
       this.status = status;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getMacAddress() {
        return this.macAddress;
    }
    
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }




}


