package com.scyllamobile.model;
// Generated Jun 8, 2017 5:46:44 AM by Hibernate Tools 4.3.1



/**
 * Menutree generated by hbm2java
 */
public class Menutree  implements java.io.Serializable {


     private MenutreeId id;
     private Menuuser menuuser;

    public Menutree() {
    }

    public Menutree(MenutreeId id, Menuuser menuuser) {
       this.id = id;
       this.menuuser = menuuser;
    }
   
    public MenutreeId getId() {
        return this.id;
    }
    
    public void setId(MenutreeId id) {
        this.id = id;
    }
    public Menuuser getMenuuser() {
        return this.menuuser;
    }
    
    public void setMenuuser(Menuuser menuuser) {
        this.menuuser = menuuser;
    }




}


