package com.scyllamobile.model;
// Generated Jun 8, 2017 5:46:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menuuser generated by hbm2java
 */
public class Menuuser  implements java.io.Serializable {


     private String menuId;
     private String menuName;
     private String menuAddress;
     private String menuParent;
     private Set menutrees = new HashSet(0);

    public Menuuser() {
    }

	
    public Menuuser(String menuId, String menuName, String menuAddress) {
        this.menuId = menuId;
        this.menuName = menuName;
        this.menuAddress = menuAddress;
    }
    public Menuuser(String menuId, String menuName, String menuAddress, String menuParent, Set menutrees) {
       this.menuId = menuId;
       this.menuName = menuName;
       this.menuAddress = menuAddress;
       this.menuParent = menuParent;
       this.menutrees = menutrees;
    }
   
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public String getMenuAddress() {
        return this.menuAddress;
    }
    
    public void setMenuAddress(String menuAddress) {
        this.menuAddress = menuAddress;
    }
    public String getMenuParent() {
        return this.menuParent;
    }
    
    public void setMenuParent(String menuParent) {
        this.menuParent = menuParent;
    }
    public Set getMenutrees() {
        return this.menutrees;
    }
    
    public void setMenutrees(Set menutrees) {
        this.menutrees = menutrees;
    }




}


