package com.scyllamobile.model;
// Generated Jun 8, 2017 5:46:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private String id;
     private String name;
     private Set userses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(String id) {
        this.id = id;
    }
    public Roles(String id, String name, Set userses) {
       this.id = id;
       this.name = name;
       this.userses = userses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


