package com.scyllamobile.model;
// Generated May 9, 2017 11:10:35 AM by Hibernate Tools 4.3.1



/**
 * TGroup generated by hbm2java
 */
public class TGroup  implements java.io.Serializable {


     private String groupid;
     private String sellerid;
     private String groupname;
     private String description;
     private Integer status;

    public TGroup() {
    }

	
    public TGroup(String groupid, String sellerid) {
        this.groupid = groupid;
        this.sellerid = sellerid;
    }
    public TGroup(String groupid, String sellerid, String groupname, String description, Integer status) {
       this.groupid = groupid;
       this.sellerid = sellerid;
       this.groupname = groupname;
       this.description = description;
       this.status = status;
    }
   
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }
    public String getSellerid() {
        return this.sellerid;
    }
    
    public void setSellerid(String sellerid) {
        this.sellerid = sellerid;
    }
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


