package com.scyllamobile.model;
// Generated May 23, 2017 2:27:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TGroup generated by hbm2java
 */
public class TGroup  implements java.io.Serializable {


     private String groupid;
     private String sellerid;
     private String groupname;
     private String description;
     private Integer status;
     private String tes;
     private Set TProducts = new HashSet(0);

    public TGroup() {
    }

	
    public TGroup(String groupid, String sellerid) {
        this.groupid = groupid;
        this.sellerid = sellerid;
    }
    public TGroup(String groupid, String sellerid, String groupname, String description, Integer status, String tes, Set TProducts) {
       this.groupid = groupid;
       this.sellerid = sellerid;
       this.groupname = groupname;
       this.description = description;
       this.status = status;
       this.tes = tes;
       this.TProducts = TProducts;
    }
   
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }
    public String getSellerid() {
        return this.sellerid;
    }
    
    public void setSellerid(String sellerid) {
        this.sellerid = sellerid;
    }
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getTes() {
        return this.tes;
    }
    
    public void setTes(String tes) {
        this.tes = tes;
    }
    public Set getTProducts() {
        return this.TProducts;
    }
    
    public void setTProducts(Set TProducts) {
        this.TProducts = TProducts;
    }




}


