package com.scyllamobile.model;
// Generated May 23, 2017 2:27:59 PM by Hibernate Tools 4.3.1



/**
 * TProduct generated by hbm2java
 */
public class TProduct  implements java.io.Serializable {


     private String idProduct;
     private TGroup TGroup;
     private TUnit TUnit;
     private String prodName;
     private String prodCode;
     private String info;
     private String valuta;
     private Long harga;
     private Integer stok;
     private String pict;
     private String condition;
     private Integer status;
     private String tes;

    public TProduct() {
    }

	
    public TProduct(String idProduct, TGroup TGroup, TUnit TUnit, String prodName, String prodCode) {
        this.idProduct = idProduct;
        this.TGroup = TGroup;
        this.TUnit = TUnit;
        this.prodName = prodName;
        this.prodCode = prodCode;
    }
    public TProduct(String idProduct, TGroup TGroup, TUnit TUnit, String prodName, String prodCode, String info, String valuta, Long harga, Integer stok, String pict, String condition, Integer status, String tes) {
       this.idProduct = idProduct;
       this.TGroup = TGroup;
       this.TUnit = TUnit;
       this.prodName = prodName;
       this.prodCode = prodCode;
       this.info = info;
       this.valuta = valuta;
       this.harga = harga;
       this.stok = stok;
       this.pict = pict;
       this.condition = condition;
       this.status = status;
       this.tes = tes;
    }
   
    public String getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(String idProduct) {
        this.idProduct = idProduct;
    }
    public TGroup getTGroup() {
        return this.TGroup;
    }
    
    public void setTGroup(TGroup TGroup) {
        this.TGroup = TGroup;
    }
    public TUnit getTUnit() {
        return this.TUnit;
    }
    
    public void setTUnit(TUnit TUnit) {
        this.TUnit = TUnit;
    }
    public String getProdName() {
        return this.prodName;
    }
    
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }
    public String getProdCode() {
        return this.prodCode;
    }
    
    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public String getValuta() {
        return this.valuta;
    }
    
    public void setValuta(String valuta) {
        this.valuta = valuta;
    }
    public Long getHarga() {
        return this.harga;
    }
    
    public void setHarga(Long harga) {
        this.harga = harga;
    }
    public Integer getStok() {
        return this.stok;
    }
    
    public void setStok(Integer stok) {
        this.stok = stok;
    }
    public String getPict() {
        return this.pict;
    }
    
    public void setPict(String pict) {
        this.pict = pict;
    }
    public String getCondition() {
        return this.condition;
    }
    
    public void setCondition(String condition) {
        this.condition = condition;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getTes() {
        return this.tes;
    }
    
    public void setTes(String tes) {
        this.tes = tes;
    }




}


