package com.scyllamobile.model;
// Generated May 9, 2017 11:10:35 AM by Hibernate Tools 4.3.1



/**
 * TProduct generated by hbm2java
 */
public class TProduct  implements java.io.Serializable {


     private String idProduct;
     private String prodName;
     private String prodCode;
     private String groupid;
     private String unitid;
     private String info;
     private String valuta;
     private Long harga;
     private Integer stok;
     private String pict;
     private String condition;
     private Integer status;

    public TProduct() {
    }

	
    public TProduct(String idProduct, String prodName, String prodCode, String groupid, String unitid) {
        this.idProduct = idProduct;
        this.prodName = prodName;
        this.prodCode = prodCode;
        this.groupid = groupid;
        this.unitid = unitid;
    }
    public TProduct(String idProduct, String prodName, String prodCode, String groupid, String unitid, String info, String valuta, Long harga, Integer stok, String pict, String condition, Integer status) {
       this.idProduct = idProduct;
       this.prodName = prodName;
       this.prodCode = prodCode;
       this.groupid = groupid;
       this.unitid = unitid;
       this.info = info;
       this.valuta = valuta;
       this.harga = harga;
       this.stok = stok;
       this.pict = pict;
       this.condition = condition;
       this.status = status;
    }
   
    public String getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(String idProduct) {
        this.idProduct = idProduct;
    }
    public String getProdName() {
        return this.prodName;
    }
    
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }
    public String getProdCode() {
        return this.prodCode;
    }
    
    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }
    public String getUnitid() {
        return this.unitid;
    }
    
    public void setUnitid(String unitid) {
        this.unitid = unitid;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public String getValuta() {
        return this.valuta;
    }
    
    public void setValuta(String valuta) {
        this.valuta = valuta;
    }
    public Long getHarga() {
        return this.harga;
    }
    
    public void setHarga(Long harga) {
        this.harga = harga;
    }
    public Integer getStok() {
        return this.stok;
    }
    
    public void setStok(Integer stok) {
        this.stok = stok;
    }
    public String getPict() {
        return this.pict;
    }
    
    public void setPict(String pict) {
        this.pict = pict;
    }
    public String getCondition() {
        return this.condition;
    }
    
    public void setCondition(String condition) {
        this.condition = condition;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


