package com.scyllamobile.model;
// Generated May 23, 2017 2:27:59 PM by Hibernate Tools 4.3.1



/**
 * TTreeMenu generated by hbm2java
 */
public class TTreeMenu  implements java.io.Serializable {


     private TTreeMenuId id;

    public TTreeMenu() {
    }

    public TTreeMenu(TTreeMenuId id) {
       this.id = id;
    }
   
    public TTreeMenuId getId() {
        return this.id;
    }
    
    public void setId(TTreeMenuId id) {
        this.id = id;
    }




}


