package com.scyllamobile.model;
// Generated May 9, 2017 11:10:35 AM by Hibernate Tools 4.3.1



/**
 * TUnit generated by hbm2java
 */
public class TUnit  implements java.io.Serializable {


     private String unitid;
     private String sellerid;
     private String unitname;
     private String description;
     private Integer status;

    public TUnit() {
    }

	
    public TUnit(String unitid, String sellerid) {
        this.unitid = unitid;
        this.sellerid = sellerid;
    }
    public TUnit(String unitid, String sellerid, String unitname, String description, Integer status) {
       this.unitid = unitid;
       this.sellerid = sellerid;
       this.unitname = unitname;
       this.description = description;
       this.status = status;
    }
   
    public String getUnitid() {
        return this.unitid;
    }
    
    public void setUnitid(String unitid) {
        this.unitid = unitid;
    }
    public String getSellerid() {
        return this.sellerid;
    }
    
    public void setSellerid(String sellerid) {
        this.sellerid = sellerid;
    }
    public String getUnitname() {
        return this.unitname;
    }
    
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


