package com.scyllamobile.model;
// Generated May 23, 2017 2:27:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TUnit generated by hbm2java
 */
public class TUnit  implements java.io.Serializable {


     private String unitid;
     private String sellerid;
     private String unitname;
     private String description;
     private Integer status;
     private Set TProducts = new HashSet(0);

    public TUnit() {
    }

	
    public TUnit(String unitid, String sellerid) {
        this.unitid = unitid;
        this.sellerid = sellerid;
    }
    public TUnit(String unitid, String sellerid, String unitname, String description, Integer status, Set TProducts) {
       this.unitid = unitid;
       this.sellerid = sellerid;
       this.unitname = unitname;
       this.description = description;
       this.status = status;
       this.TProducts = TProducts;
    }
   
    public String getUnitid() {
        return this.unitid;
    }
    
    public void setUnitid(String unitid) {
        this.unitid = unitid;
    }
    public String getSellerid() {
        return this.sellerid;
    }
    
    public void setSellerid(String sellerid) {
        this.sellerid = sellerid;
    }
    public String getUnitname() {
        return this.unitname;
    }
    
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getTProducts() {
        return this.TProducts;
    }
    
    public void setTProducts(Set TProducts) {
        this.TProducts = TProducts;
    }




}


