package com.scyllamobile.model;
// Generated May 9, 2017 11:10:35 AM by Hibernate Tools 4.3.1



/**
 * TUserMenu generated by hbm2java
 */
public class TUserMenu  implements java.io.Serializable {


     private String menuId;
     private String menuName;
     private String menuAddress;
     private String menuParent;
     private String menuLink;

    public TUserMenu() {
    }

	
    public TUserMenu(String menuId, String menuName, String menuAddress) {
        this.menuId = menuId;
        this.menuName = menuName;
        this.menuAddress = menuAddress;
    }
    public TUserMenu(String menuId, String menuName, String menuAddress, String menuParent, String menuLink) {
       this.menuId = menuId;
       this.menuName = menuName;
       this.menuAddress = menuAddress;
       this.menuParent = menuParent;
       this.menuLink = menuLink;
    }
   
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public String getMenuAddress() {
        return this.menuAddress;
    }
    
    public void setMenuAddress(String menuAddress) {
        this.menuAddress = menuAddress;
    }
    public String getMenuParent() {
        return this.menuParent;
    }
    
    public void setMenuParent(String menuParent) {
        this.menuParent = menuParent;
    }
    public String getMenuLink() {
        return this.menuLink;
    }
    
    public void setMenuLink(String menuLink) {
        this.menuLink = menuLink;
    }




}


