package com.scyllamobile.model;
// Generated May 23, 2017 2:27:59 PM by Hibernate Tools 4.3.1



/**
 * TUserGroup generated by hbm2java
 */
public class TUserGroup  implements java.io.Serializable {


     private String userGroupId;
     private String status;
     private String description;

    public TUserGroup() {
    }

    public TUserGroup(String userGroupId, String status, String description) {
       this.userGroupId = userGroupId;
       this.status = status;
       this.description = description;
    }
   
    public String getUserGroupId() {
        return this.userGroupId;
    }
    
    public void setUserGroupId(String userGroupId) {
        this.userGroupId = userGroupId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


