package com.scyllamobile.model;
// Generated Jun 8, 2017 5:46:44 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private BigDecimal id;
     private Roles roles;
     private String address;
     private String code;
     private String email;
     private String fullName;
     private Serializable lastLogin;
     private String passwordHash;
     private Long status;
     private Set deviceses = new HashSet(0);

    public Users() {
    }

	
    public Users(BigDecimal id) {
        this.id = id;
    }
    public Users(BigDecimal id, Roles roles, String address, String code, String email, String fullName, Serializable lastLogin, String passwordHash, Long status, Set deviceses) {
       this.id = id;
       this.roles = roles;
       this.address = address;
       this.code = code;
       this.email = email;
       this.fullName = fullName;
       this.lastLogin = lastLogin;
       this.passwordHash = passwordHash;
       this.status = status;
       this.deviceses = deviceses;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Serializable getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Serializable lastLogin) {
        this.lastLogin = lastLogin;
    }
    public String getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    public Set getDeviceses() {
        return this.deviceses;
    }
    
    public void setDeviceses(Set deviceses) {
        this.deviceses = deviceses;
    }




}


