package com.scyllamobile.modelo;
// Generated May 30, 2017 1:15:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mblfbrand generated by hbm2java
 */
public class Mblfbrand  implements java.io.Serializable {


     private BigDecimal id;
     private String mtgl;
     private String mslsno;
     private String brand;
     private String brandname;

    public Mblfbrand() {
    }

	
    public Mblfbrand(BigDecimal id) {
        this.id = id;
    }
    public Mblfbrand(BigDecimal id, String mtgl, String mslsno, String brand, String brandname) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.brand = brand;
       this.brandname = brandname;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(String mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getBrandname() {
        return this.brandname;
    }
    
    public void setBrandname(String brandname) {
        this.brandname = brandname;
    }




}


