package com.scyllamobile.modelo;
// Generated Jun 8, 2017 5:46:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mblfarcndn generated by hbm2java
 */
public class Mblfarcndn  implements java.io.Serializable {


     private BigDecimal id;
     private String mtgl;
     private String mslsno;
     private String docno;
     private String docdate;
     private String flag1;
     private String custno;
     private BigDecimal amount;
     private String remark;
     private String kode;
     private BigDecimal payamt;
     private String flag2;

    public Mblfarcndn() {
    }

	
    public Mblfarcndn(BigDecimal id) {
        this.id = id;
    }
    public Mblfarcndn(BigDecimal id, String mtgl, String mslsno, String docno, String docdate, String flag1, String custno, BigDecimal amount, String remark, String kode, BigDecimal payamt, String flag2) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.docno = docno;
       this.docdate = docdate;
       this.flag1 = flag1;
       this.custno = custno;
       this.amount = amount;
       this.remark = remark;
       this.kode = kode;
       this.payamt = payamt;
       this.flag2 = flag2;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(String mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getDocno() {
        return this.docno;
    }
    
    public void setDocno(String docno) {
        this.docno = docno;
    }
    public String getDocdate() {
        return this.docdate;
    }
    
    public void setDocdate(String docdate) {
        this.docdate = docdate;
    }
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    public String getCustno() {
        return this.custno;
    }
    
    public void setCustno(String custno) {
        this.custno = custno;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public String getKode() {
        return this.kode;
    }
    
    public void setKode(String kode) {
        this.kode = kode;
    }
    public BigDecimal getPayamt() {
        return this.payamt;
    }
    
    public void setPayamt(BigDecimal payamt) {
        this.payamt = payamt;
    }
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }




}


