package com.scyllamobile.modelo;
// Generated May 30, 2017 1:15:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mblfcustmst generated by hbm2java
 */
public class Mblfcustmst  implements java.io.Serializable {


     private BigDecimal id;
     private String mtgl;
     private String mslsno;
     private String custno;
     private String data01;
     private String custname;
     private String custadd1;
     private String custadd2;
     private String ccity;
     private String ccontact;
     private String cphone1;
     private String cfaxno;
     private BigDecimal cterm;
     private BigDecimal climit;
     private String flaglimit;
     private String gdisc;
     private String typeout;
     private String grupout;
     private String gharga;
     private String flagvisit;
     private String vdisc;
     private String daycode;
     private String info1;
     private String info2;
     private String flagpay;
     private String flagout;
     private BigDecimal rpp;
     private BigDecimal lsales;
     private String visit1;
     private String visit2;
     private String visit3;
     private String visit4;
     private String ldatetrs;
     private String lokasi;
     private String distrik;
     private String beat;
     private String subbeat;
     private String klasif;
     private String kindus;
     private String kpasar;
     private String flagcust;
     private String flagemb;
     private String la;
     private String lg;

    public Mblfcustmst() {
    }

	
    public Mblfcustmst(BigDecimal id) {
        this.id = id;
    }
    public Mblfcustmst(BigDecimal id, String mtgl, String mslsno, String custno, String data01, String custname, String custadd1, String custadd2, String ccity, String ccontact, String cphone1, String cfaxno, BigDecimal cterm, BigDecimal climit, String flaglimit, String gdisc, String typeout, String grupout, String gharga, String flagvisit, String vdisc, String daycode, String info1, String info2, String flagpay, String flagout, BigDecimal rpp, BigDecimal lsales, String visit1, String visit2, String visit3, String visit4, String ldatetrs, String lokasi, String distrik, String beat, String subbeat, String klasif, String kindus, String kpasar, String flagcust, String flagemb, String la, String lg) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.custno = custno;
       this.data01 = data01;
       this.custname = custname;
       this.custadd1 = custadd1;
       this.custadd2 = custadd2;
       this.ccity = ccity;
       this.ccontact = ccontact;
       this.cphone1 = cphone1;
       this.cfaxno = cfaxno;
       this.cterm = cterm;
       this.climit = climit;
       this.flaglimit = flaglimit;
       this.gdisc = gdisc;
       this.typeout = typeout;
       this.grupout = grupout;
       this.gharga = gharga;
       this.flagvisit = flagvisit;
       this.vdisc = vdisc;
       this.daycode = daycode;
       this.info1 = info1;
       this.info2 = info2;
       this.flagpay = flagpay;
       this.flagout = flagout;
       this.rpp = rpp;
       this.lsales = lsales;
       this.visit1 = visit1;
       this.visit2 = visit2;
       this.visit3 = visit3;
       this.visit4 = visit4;
       this.ldatetrs = ldatetrs;
       this.lokasi = lokasi;
       this.distrik = distrik;
       this.beat = beat;
       this.subbeat = subbeat;
       this.klasif = klasif;
       this.kindus = kindus;
       this.kpasar = kpasar;
       this.flagcust = flagcust;
       this.flagemb = flagemb;
       this.la = la;
       this.lg = lg;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(String mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getCustno() {
        return this.custno;
    }
    
    public void setCustno(String custno) {
        this.custno = custno;
    }
    public String getData01() {
        return this.data01;
    }
    
    public void setData01(String data01) {
        this.data01 = data01;
    }
    public String getCustname() {
        return this.custname;
    }
    
    public void setCustname(String custname) {
        this.custname = custname;
    }
    public String getCustadd1() {
        return this.custadd1;
    }
    
    public void setCustadd1(String custadd1) {
        this.custadd1 = custadd1;
    }
    public String getCustadd2() {
        return this.custadd2;
    }
    
    public void setCustadd2(String custadd2) {
        this.custadd2 = custadd2;
    }
    public String getCcity() {
        return this.ccity;
    }
    
    public void setCcity(String ccity) {
        this.ccity = ccity;
    }
    public String getCcontact() {
        return this.ccontact;
    }
    
    public void setCcontact(String ccontact) {
        this.ccontact = ccontact;
    }
    public String getCphone1() {
        return this.cphone1;
    }
    
    public void setCphone1(String cphone1) {
        this.cphone1 = cphone1;
    }
    public String getCfaxno() {
        return this.cfaxno;
    }
    
    public void setCfaxno(String cfaxno) {
        this.cfaxno = cfaxno;
    }
    public BigDecimal getCterm() {
        return this.cterm;
    }
    
    public void setCterm(BigDecimal cterm) {
        this.cterm = cterm;
    }
    public BigDecimal getClimit() {
        return this.climit;
    }
    
    public void setClimit(BigDecimal climit) {
        this.climit = climit;
    }
    public String getFlaglimit() {
        return this.flaglimit;
    }
    
    public void setFlaglimit(String flaglimit) {
        this.flaglimit = flaglimit;
    }
    public String getGdisc() {
        return this.gdisc;
    }
    
    public void setGdisc(String gdisc) {
        this.gdisc = gdisc;
    }
    public String getTypeout() {
        return this.typeout;
    }
    
    public void setTypeout(String typeout) {
        this.typeout = typeout;
    }
    public String getGrupout() {
        return this.grupout;
    }
    
    public void setGrupout(String grupout) {
        this.grupout = grupout;
    }
    public String getGharga() {
        return this.gharga;
    }
    
    public void setGharga(String gharga) {
        this.gharga = gharga;
    }
    public String getFlagvisit() {
        return this.flagvisit;
    }
    
    public void setFlagvisit(String flagvisit) {
        this.flagvisit = flagvisit;
    }
    public String getVdisc() {
        return this.vdisc;
    }
    
    public void setVdisc(String vdisc) {
        this.vdisc = vdisc;
    }
    public String getDaycode() {
        return this.daycode;
    }
    
    public void setDaycode(String daycode) {
        this.daycode = daycode;
    }
    public String getInfo1() {
        return this.info1;
    }
    
    public void setInfo1(String info1) {
        this.info1 = info1;
    }
    public String getInfo2() {
        return this.info2;
    }
    
    public void setInfo2(String info2) {
        this.info2 = info2;
    }
    public String getFlagpay() {
        return this.flagpay;
    }
    
    public void setFlagpay(String flagpay) {
        this.flagpay = flagpay;
    }
    public String getFlagout() {
        return this.flagout;
    }
    
    public void setFlagout(String flagout) {
        this.flagout = flagout;
    }
    public BigDecimal getRpp() {
        return this.rpp;
    }
    
    public void setRpp(BigDecimal rpp) {
        this.rpp = rpp;
    }
    public BigDecimal getLsales() {
        return this.lsales;
    }
    
    public void setLsales(BigDecimal lsales) {
        this.lsales = lsales;
    }
    public String getVisit1() {
        return this.visit1;
    }
    
    public void setVisit1(String visit1) {
        this.visit1 = visit1;
    }
    public String getVisit2() {
        return this.visit2;
    }
    
    public void setVisit2(String visit2) {
        this.visit2 = visit2;
    }
    public String getVisit3() {
        return this.visit3;
    }
    
    public void setVisit3(String visit3) {
        this.visit3 = visit3;
    }
    public String getVisit4() {
        return this.visit4;
    }
    
    public void setVisit4(String visit4) {
        this.visit4 = visit4;
    }
    public String getLdatetrs() {
        return this.ldatetrs;
    }
    
    public void setLdatetrs(String ldatetrs) {
        this.ldatetrs = ldatetrs;
    }
    public String getLokasi() {
        return this.lokasi;
    }
    
    public void setLokasi(String lokasi) {
        this.lokasi = lokasi;
    }
    public String getDistrik() {
        return this.distrik;
    }
    
    public void setDistrik(String distrik) {
        this.distrik = distrik;
    }
    public String getBeat() {
        return this.beat;
    }
    
    public void setBeat(String beat) {
        this.beat = beat;
    }
    public String getSubbeat() {
        return this.subbeat;
    }
    
    public void setSubbeat(String subbeat) {
        this.subbeat = subbeat;
    }
    public String getKlasif() {
        return this.klasif;
    }
    
    public void setKlasif(String klasif) {
        this.klasif = klasif;
    }
    public String getKindus() {
        return this.kindus;
    }
    
    public void setKindus(String kindus) {
        this.kindus = kindus;
    }
    public String getKpasar() {
        return this.kpasar;
    }
    
    public void setKpasar(String kpasar) {
        this.kpasar = kpasar;
    }
    public String getFlagcust() {
        return this.flagcust;
    }
    
    public void setFlagcust(String flagcust) {
        this.flagcust = flagcust;
    }
    public String getFlagemb() {
        return this.flagemb;
    }
    
    public void setFlagemb(String flagemb) {
        this.flagemb = flagemb;
    }
    public String getLa() {
        return this.la;
    }
    
    public void setLa(String la) {
        this.la = la;
    }
    public String getLg() {
        return this.lg;
    }
    
    public void setLg(String lg) {
        this.lg = lg;
    }




}


