package com.scyllamobile.modelo;
// Generated May 30, 2017 1:15:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mblftbank generated by hbm2java
 */
public class Mblftbank  implements java.io.Serializable {


     private BigDecimal id;
     private String mtgl;
     private String mslsno;
     private String bankNo;
     private String bankName;

    public Mblftbank() {
    }

	
    public Mblftbank(BigDecimal id) {
        this.id = id;
    }
    public Mblftbank(BigDecimal id, String mtgl, String mslsno, String bankNo, String bankName) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.bankNo = bankNo;
       this.bankName = bankName;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(String mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getBankNo() {
        return this.bankNo;
    }
    
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo;
    }
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }




}


