package com.scyllamobile.modelo;
// Generated Jun 8, 2017 5:46:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mblfdiscd6 generated by hbm2java
 */
public class Mblfdiscd6  implements java.io.Serializable {


     private BigDecimal id;
     private String mtgl;
     private String mslsno;
     private String kode;
     private String pcode;
     private BigDecimal xno;
     private BigDecimal minqty;
     private BigDecimal maxqty;
     private String xminqty;
     private String xmaxqty;
     private BigDecimal kpercent;

    public Mblfdiscd6() {
    }

	
    public Mblfdiscd6(BigDecimal id) {
        this.id = id;
    }
    public Mblfdiscd6(BigDecimal id, String mtgl, String mslsno, String kode, String pcode, BigDecimal xno, BigDecimal minqty, BigDecimal maxqty, String xminqty, String xmaxqty, BigDecimal kpercent) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.kode = kode;
       this.pcode = pcode;
       this.xno = xno;
       this.minqty = minqty;
       this.maxqty = maxqty;
       this.xminqty = xminqty;
       this.xmaxqty = xmaxqty;
       this.kpercent = kpercent;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(String mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getKode() {
        return this.kode;
    }
    
    public void setKode(String kode) {
        this.kode = kode;
    }
    public String getPcode() {
        return this.pcode;
    }
    
    public void setPcode(String pcode) {
        this.pcode = pcode;
    }
    public BigDecimal getXno() {
        return this.xno;
    }
    
    public void setXno(BigDecimal xno) {
        this.xno = xno;
    }
    public BigDecimal getMinqty() {
        return this.minqty;
    }
    
    public void setMinqty(BigDecimal minqty) {
        this.minqty = minqty;
    }
    public BigDecimal getMaxqty() {
        return this.maxqty;
    }
    
    public void setMaxqty(BigDecimal maxqty) {
        this.maxqty = maxqty;
    }
    public String getXminqty() {
        return this.xminqty;
    }
    
    public void setXminqty(String xminqty) {
        this.xminqty = xminqty;
    }
    public String getXmaxqty() {
        return this.xmaxqty;
    }
    
    public void setXmaxqty(String xmaxqty) {
        this.xmaxqty = xmaxqty;
    }
    public BigDecimal getKpercent() {
        return this.kpercent;
    }
    
    public void setKpercent(BigDecimal kpercent) {
        this.kpercent = kpercent;
    }




}


