package com.scyllamobile.modelo;
// Generated May 30, 2017 1:15:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mblfmaster generated by hbm2java
 */
public class Mblfmaster  implements java.io.Serializable {


     private BigDecimal id;
     private String mtgl;
     private String mslsno;
     private String pcode;
     private String data1;
     private String pcodename;
     private String unit1;
     private String unit2;
     private String unit3;
     private BigDecimal convunit2;
     private BigDecimal convunit3;
     private BigDecimal sellprice1;
     private BigDecimal sellprice2;
     private BigDecimal sellprice3;
     private BigDecimal pbmjual;
     private BigDecimal stock;
     private String xstock;
     private String flagfocus;
     private String prlin;
     private String brand;
     private BigDecimal ppn;
     private BigDecimal ppndp;
     private String embincId;
     private String embexcId;

    public Mblfmaster() {
    }

	
    public Mblfmaster(BigDecimal id) {
        this.id = id;
    }
    public Mblfmaster(BigDecimal id, String mtgl, String mslsno, String pcode, String data1, String pcodename, String unit1, String unit2, String unit3, BigDecimal convunit2, BigDecimal convunit3, BigDecimal sellprice1, BigDecimal sellprice2, BigDecimal sellprice3, BigDecimal pbmjual, BigDecimal stock, String xstock, String flagfocus, String prlin, String brand, BigDecimal ppn, BigDecimal ppndp, String embincId, String embexcId) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.pcode = pcode;
       this.data1 = data1;
       this.pcodename = pcodename;
       this.unit1 = unit1;
       this.unit2 = unit2;
       this.unit3 = unit3;
       this.convunit2 = convunit2;
       this.convunit3 = convunit3;
       this.sellprice1 = sellprice1;
       this.sellprice2 = sellprice2;
       this.sellprice3 = sellprice3;
       this.pbmjual = pbmjual;
       this.stock = stock;
       this.xstock = xstock;
       this.flagfocus = flagfocus;
       this.prlin = prlin;
       this.brand = brand;
       this.ppn = ppn;
       this.ppndp = ppndp;
       this.embincId = embincId;
       this.embexcId = embexcId;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(String mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getPcode() {
        return this.pcode;
    }
    
    public void setPcode(String pcode) {
        this.pcode = pcode;
    }
    public String getData1() {
        return this.data1;
    }
    
    public void setData1(String data1) {
        this.data1 = data1;
    }
    public String getPcodename() {
        return this.pcodename;
    }
    
    public void setPcodename(String pcodename) {
        this.pcodename = pcodename;
    }
    public String getUnit1() {
        return this.unit1;
    }
    
    public void setUnit1(String unit1) {
        this.unit1 = unit1;
    }
    public String getUnit2() {
        return this.unit2;
    }
    
    public void setUnit2(String unit2) {
        this.unit2 = unit2;
    }
    public String getUnit3() {
        return this.unit3;
    }
    
    public void setUnit3(String unit3) {
        this.unit3 = unit3;
    }
    public BigDecimal getConvunit2() {
        return this.convunit2;
    }
    
    public void setConvunit2(BigDecimal convunit2) {
        this.convunit2 = convunit2;
    }
    public BigDecimal getConvunit3() {
        return this.convunit3;
    }
    
    public void setConvunit3(BigDecimal convunit3) {
        this.convunit3 = convunit3;
    }
    public BigDecimal getSellprice1() {
        return this.sellprice1;
    }
    
    public void setSellprice1(BigDecimal sellprice1) {
        this.sellprice1 = sellprice1;
    }
    public BigDecimal getSellprice2() {
        return this.sellprice2;
    }
    
    public void setSellprice2(BigDecimal sellprice2) {
        this.sellprice2 = sellprice2;
    }
    public BigDecimal getSellprice3() {
        return this.sellprice3;
    }
    
    public void setSellprice3(BigDecimal sellprice3) {
        this.sellprice3 = sellprice3;
    }
    public BigDecimal getPbmjual() {
        return this.pbmjual;
    }
    
    public void setPbmjual(BigDecimal pbmjual) {
        this.pbmjual = pbmjual;
    }
    public BigDecimal getStock() {
        return this.stock;
    }
    
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }
    public String getXstock() {
        return this.xstock;
    }
    
    public void setXstock(String xstock) {
        this.xstock = xstock;
    }
    public String getFlagfocus() {
        return this.flagfocus;
    }
    
    public void setFlagfocus(String flagfocus) {
        this.flagfocus = flagfocus;
    }
    public String getPrlin() {
        return this.prlin;
    }
    
    public void setPrlin(String prlin) {
        this.prlin = prlin;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public BigDecimal getPpn() {
        return this.ppn;
    }
    
    public void setPpn(BigDecimal ppn) {
        this.ppn = ppn;
    }
    public BigDecimal getPpndp() {
        return this.ppndp;
    }
    
    public void setPpndp(BigDecimal ppndp) {
        this.ppndp = ppndp;
    }
    public String getEmbincId() {
        return this.embincId;
    }
    
    public void setEmbincId(String embincId) {
        this.embincId = embincId;
    }
    public String getEmbexcId() {
        return this.embexcId;
    }
    
    public void setEmbexcId(String embexcId) {
        this.embexcId = embexcId;
    }




}


